Rewards = {
	[1] = { ["item"] = "burgershotpass", ["amount"] = 3 },
	[2] = { ["item"] = "dollars", ["amount"] = 10000 },
	[3] = { ["item"] = "dollars", ["amount"] = 10000 },
	[4] = { ["item"] = "luckywheelpass", ["amount"] = 3 },
	[5] = { ["item"] = "gemstone", ["amount"] = 10 },
	[6] = { ["item"] = "mushroomteaplus", ["amount"] = 1 },
	[7] = { ["item"] = "dollars", ["amount"] = 10000 },
	[8] = { ["item"] = "dollars", ["amount"] = 10000 },
	[9] = { ["item"] = "dollars", ["amount"] = 10000 },
	[10] = { ["item"] = "dollars", ["amount"] = 10000 },
	[11] = { ["item"] = "gemstone", ["amount"] = 10 },
	[12] = { ["item"] = "mushroomteaplus", ["amount"] = 2 },
	[13] = { ["item"] = "luckywheelpass", ["amount"] = 3 },
	[14] = { ["item"] = "dollars", ["amount"] = 15000 },
	[15] = { ["item"] = "dollars", ["amount"] = 20000 },
	[16] = { ["item"] = "dollars", ["amount"] = 25000 },
	[17] = { ["item"] = "gemstone", ["amount"] = 10 },
	[18] = { ["item"] = "mushroomteaplus", ["amount"] = 3 },
	[19] = { ["item"] = "luckywheelpass", ["amount"] = 3 },
	[20] = { ["item"] = "burgershotpass", ["amount"] = 3 },
	[21] = { ["item"] = "dollars", ["amount"] = 10000 },
	[22] = { ["item"] = "dollars", ["amount"] = 10000 },
	[23] = { ["item"] = "gemstone", ["amount"] = 10 },
	[24] = { ["item"] = "rentalveh", ["amount"] = 1 }
}
